; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = cyd28

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  tzapu/WiFiManager @ ^2.0.17
  https://github.com/PaulStoffregen/XPT2046_Touchscreen
monitor_speed = 115200
build_flags =
  -include include/config.h

[env:cyd28]
build_flags =
  ${env.build_flags}
  -D CYD_BOARD_28

[env:cyd40]
build_flags =
  ${env.build_flags}
  -D CYD_BOARD_40
